name: Misc
authors: Darcy Manoel
homepage: https://github.com/Adde-Endless-Sky/Misc
license: GPL-3.0-or-later
version: 1edbadcf1768f3b93cf64160233978cb835e2a5d
shortDescription: A mix of varied content which isn't currently categorized.
description: Any Adde content that doesn't fit in another or deserve it's own repository.
  This can be anything from new systems to new missions.

  This plugin is part of the Adde Endless Sky collection.
url: https://github.com/Adde-Endless-Sky/Misc/archive/1edbadcf1768f3b93cf64160233978cb835e2a5d.zip
iconUrl: https://github.com/Adde-Endless-Sky/Misc/raw/1edbadcf1768f3b93cf64160233978cb835e2a5d/icon.png
autoupdate:
  type: commit
  branch: main
  url: https://github.com/Adde-Endless-Sky/Misc/archive/$version.zip
  iconUrl: https://github.com/Adde-Endless-Sky/Misc/raw/$version/icon.png
